# Generated by Django 4.1.3 on 2022-12-18 10:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='gifts',
            name='id_category',
        ),
    ]
