# Generated by Django 4.1.3 on 2023-01-04 18:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_remove_gifts_id_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='gifts',
            name='description',
            field=models.CharField(default='test', max_length=255),
            preserve_default=False,
        ),
    ]
