# Generated by Django 4.1.3 on 2023-01-09 20:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_paymentmethods'),
    ]

    operations = [
        migrations.AddField(
            model_name='users',
            name='billing_address',
            field=models.CharField(default='', max_length=255),
        ),
        migrations.AddField(
            model_name='users',
            name='billing_city',
            field=models.CharField(default='', max_length=255),
        ),
        migrations.AddField(
            model_name='users',
            name='billing_name',
            field=models.CharField(default='', max_length=255),
        ),
        migrations.AddField(
            model_name='users',
            name='billing_postcode',
            field=models.CharField(default='', max_length=255),
        ),
        migrations.AddField(
            model_name='users',
            name='preferred_method_id',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='api.paymentmethods'),
        ),
    ]
