# Generated by Django 4.1.3 on 2023-01-09 20:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_users_billing_address_users_billing_city_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='paymentmethods',
            name='URL',
            field=models.CharField(default=' ', max_length=255),
            preserve_default=False,
        ),
    ]
