# Generated by Django 4.1.3 on 2022-12-11 23:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_alter_events_id_event_alter_gifts_id_gift_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='users',
            name='id_role',
        ),
        migrations.DeleteModel(
            name='Roles',
        ),
    ]
