# Generated by Django 4.1.3 on 2022-12-11 23:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_remove_users_id_role_delete_roles'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='orders',
            name='id_gift',
        ),
        migrations.RemoveField(
            model_name='orders',
            name='id_user',
        ),
        migrations.RemoveField(
            model_name='usersevents',
            name='id_event',
        ),
        migrations.RemoveField(
            model_name='usersevents',
            name='id_user',
        ),
        migrations.DeleteModel(
            name='Events',
        ),
        migrations.DeleteModel(
            name='Gifts',
        ),
        migrations.DeleteModel(
            name='Orders',
        ),
        migrations.DeleteModel(
            name='Users',
        ),
        migrations.DeleteModel(
            name='UsersEvents',
        ),
    ]
